### ISSUE TITLE
response based routing in MCS

### ISSUE THREAD

**Issue by rajeshdhanda** [GoogleCloudPlatform/gke-networking-recipes#113]
**Service A** : Inference Server
**Service B** : predictor host in gpu-pool with `minReplicas: 0`, scale up on request from inference server

**Service A** internally calls **Service B**, but sometimes **Service B** is down resulting in `500: Internal Server Error` in final  response. Need to route the request in different regional cluster based on response from **Service A**.

Thanks 
![Untitled-2022-10-06-1300](https://user-images.githubusercontent.com/50963889/194261545-2743aaa4-8534-49e2-b84f-e60d5cb3b11f.svg)

**Comment by boredabdel** [comment]
Can you please explain what is the ask here ?

**Comment by rajeshdhanda** [comment]
Hi @boredabdel 
**Service A** and **Service B** are services in different node-pool in a GKE Cluster. 
**Service A** is primary service in default-pool and is always up.
**Service B** runs on GPU node ( node in gpu-pool with auto scale 0-3 ). Whenever any request is sent to **Service B**, it scales up ( gpu node is created and then pod replica ) and process the request. 
Sometimes due to `gpu resource unavailbility in node is not able to scale up`. 
**Service A**  is Kserve InferenceService calling **Service B** 
```
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: Service_A 
spec:
  predictor:
    containers:
      - name: kfserving-container
        image: gcr_path_here
        args:
          - --predictor_host=host_from_service_B
 ```
Request from client is sent to primary **Service A**.
**Service A** internally calls **Service B**, but sometimes **Service B** is not able to scale up ( gpu resource unavailbility ) resulting in `500: Internal Server Error` in final response from **Service A**.

Need to route the request in different regional cluster based on `response from Service A`.
