### ISSUE TITLE
MCI: Support for Multiple Paths Targeting Different MCSs in Rules

### ISSUE THREAD

**Issue by josedev-union** [GoogleCloudPlatform/gke-networking-recipes#200]
Hello team,

I would like to inquire if it’s possible to define rules with multiple paths that target different Multi-Cluster Services (MCSs).

For example, consider the following manifest:

```yaml
spec:
  template:
    spec:
      rules:
      - host: hello.mci.io
        http:
          paths:
          - backend:
              serviceName: auth
              servicePort: 80
            path: /auth
      - host: hello.mci.io
        http:
          paths:
          - backend:
              serviceName: bill
              servicePort: 80
            path: /bill
```

I attempted to use this configuration, and while the Load Balancer host and path rules were updated accordingly, all requests are still being routed to the default backend. I also noticed that `pathType: Prefix` is not allowed in MCI, and using asterisk (`/auth/*` and `/bill/*`) did not resolve the issue.

Could you please provide guidance on how to achieve this behavior or suggest any potential solutions?

Thank you for your assistance.
