### ISSUE TITLE
How to verify ACME challenge through MultiClusterIngress

### ISSUE THREAD

**Issue by RammusXu** [GoogleCloudPlatform/gke-networking-recipes#26]
HI, is it possible to pass cert-manager `http01` through `MultiClusterIngress`?

I tried this, but it seems not integrate to `MultiClusterIngress`.

```yaml
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: ci-http01
spec:
  acme:
    email: rammus.xu@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: issuer-account-key
    solvers:
      - http01:
          ingress:
            class: ingress-gce

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: rammus-2020-cf
  namespace: multi-cluster-demo
spec:
  secretName: rammus-2020-cf-tls
  issuerRef:
    kind: ClusterIssuer
    name: ci-http01
  commonName: mci.rammus-2020.cf
  dnsNames:
  - mci.rammus-2020.cf

---
apiVersion: networking.gke.io/v1
kind: MultiClusterIngress
metadata:
  name: foobar-ingress
  namespace: multi-cluster-demo
spec:
  template:
    spec:
      tls:
      - secretName: rammus-2020-cf-tls
      backend:
        serviceName: default-backend
        servicePort: 8080
      rules:
      - host: foo.example.com
        http:
          paths:
            - backend:
                serviceName: foo
                servicePort: 8080
      - host: bar.example.com
        http:
          paths:
            - backend:
                serviceName: bar
                servicePort: 8080
      - host: mci.rammus-2020.cf
        http:
          paths:
            - backend:
                serviceName: bar
                servicePort: 8080
```

I also try to inject this, can't work either.
```yaml
      annotations:
        cert-manager.io/cluster-issuer: ci-http01
        acme.cert-manager.io/http01-edit-in-place: "true"
```
