### ISSUE TITLE
FrontEndConfig does not create HTTPS redirect Load Balancers, only one HTTP LB

### ISSUE THREAD

**Issue by Gageperrin** [GoogleCloudPlatform/gke-networking-recipes#69]
Posted this[ originally here](https://github.com/kubernetes/ingress-gce/issues/1075), per @boredabdel 's request I am opening as an issue here.

Expected behavior: Create Load Balancing with HTTPS redirect without manual changes using manifest file annotations.

Actual behavior: Only a HTTP front-end Load Balancer is created.

-------

This is a relatively straightforward configuration. One cluster, one node, one Ingress with a FQDN.

The FrontEnd Config annotation in the Ingress YAML creates what appears in the console menu as a HTTP(S) load balancer but only has a single HTTP front-end with no certificate or SSL policy attached, despite these being annotated in the Ingress YAML. the SSL cert is stuck in provisioning as FAILED_NOT_VISIBLE because it has no Target Proxy to attach to.

[If I understand correctly from the docs here](https://cloud.google.com/kubernetes-engine/docs/how-to/ingress-features#https_redirect), two load balancers should be provisioned, one HTTP and one HTTPS. The HTTP should redirect to the HTTPS. Instead, one HTTP load balancer is created with the original Ingress backends.

The HTTP Load Balancer reports the original HTTP backends as healthy while the Ingress reports its backend services as "Unknown".

Is there something wrong with syntax or spec that is preventing the HTTPS Load Balancer from generating correctly?

The HTTP LB worked fine before the frontend config was added, but I want to force HTTPS.

Note my deployment was written through Terraform, so there may be typos in my "translation" back into YAML.

Screenshots will be attached below.

FrontEnd Config YAML:
```
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: api-ingress-frontend-config
  namespace: default
spec:
  sslPolicy: ssl-policy <--- externally created
  redirectToHttps:
    enabled: true
```

BackEnd Config YAML:
```
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: api-ingress-backend-config
  namespace: default
spec:
  healthCheck:
    checkIntervalSec: 90
    port: 8000
    type: HTTP
    requestPath: "/health/"
```

Ingress YAML: (The Terraform resource has `wait_for_load_balancer` set to true.)
```
apiVersion: v1
kind: Ingress
metadata:
  annotations:
    "kubernetes.io/ingress.class": "gce"
 # "kubernetes.io/ingress.allow-http": "false" <--- commented out because this creates a Load Balancer sync error.
    "kubernetes.io/ingress.global-static-ip-name": [pre-defined static IP]
    "networking.gke.io/frontend-config": "api-ingress-frontend-config"
    "networking.gke.io/managed-certificates": [pre-defined SSL cert for ingress subdomain]
spec:
 rule:
   host: api.example.com
   http:
     path:
       backend:
         serviceName: api-service
         servicePort: 8000
```

Service YAML:
```
apiVersion: v1
kind: Service
metadata:
  name: api-service
  labels:
    app: backend
  annotations:
    "cloud.google.com/backend-config": {"default": "api-ingress-backend-config"}
 # "cloud.google.com/neg": {ingress: true}
spec:
  selector:
    app: backend
  sessionAffinity: None
  ports:
    port: 8000
    targetPort: 8000
  type: NodePort
```

`kubectl describe crd frontendconfigs.networking.gke.io` returns the following:
```
Name:         frontendconfigs.networking.gke.io
Namespace:    
Labels:       <none>
Annotations:  <none>
API Version:  apiextensions.k8s.io/v1
Kind:         CustomResourceDefinition
Metadata:
  Creation Timestamp:  2021-10-29T12:39:10Z
  Generation:          1
  Managed Fields:
    API Version:  apiextensions.k8s.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:spec:
        f:conversion:
          .:
          f:strategy:
        f:group:
        f:names:
          f:kind:
          f:listKind:
          f:plural:
          f:singular:
        f:scope:
        f:versions:
      f:status:
        f:acceptedNames:
          f:kind:
          f:plural:
        f:conditions:
        f:storedVersions:
    Manager:         glbc
    Operation:       Update
    Time:            2021-10-29T12:48:18Z
  Resource Version:  2865
  UID:               ae694fde-68cf-4cea-ad7f-6c2f1490f8ae
Spec:
  Conversion:
    Strategy:  None
  Group:       networking.gke.io
  Names:
    Kind:       FrontendConfig
    List Kind:  FrontendConfigList
    Plural:     frontendconfigs
    Singular:   frontendconfig
  Scope:        Namespaced
  Versions:
    Name:  v1beta1
    Schema:
      openAPIV3Schema:
        Properties:
          API Version:
            Description:  APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            Type:         string
          Kind:
            Description:  Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            Type:         string
          Metadata:
            Type:  object
          Spec:
            Description:  FrontendConfigSpec is the spec for a FrontendConfig resource
            Properties:
              Redirect To Https:
                Description:  HttpsRedirectConfig representing the configuration of Https redirects
                Properties:
                  Enabled:
                    Type:  boolean
                  Response Code Name:
                    Description:  String representing the HTTP response code Options are MOVED_PERMANENTLY_DEFAULT, FOUND, TEMPORARY_REDIRECT, or PERMANENT_REDIRECT
                    Type:         string
                Required:
                  enabled
                Type:  object
              Ssl Policy:
                Type:  string
            Type:      object
          Status:
            Type:  object
        Type:      object
    Served:        true
    Storage:       true
Status:
  Accepted Names:
    Kind:       FrontendConfig
    List Kind:  FrontendConfigList
    Plural:     frontendconfigs
    Singular:   frontendconfig
  Conditions:
    Last Transition Time:  2021-10-29T12:39:10Z
    Message:               no conflicts found
    Reason:                NoConflicts
    Status:                True
    Type:                  NamesAccepted
    Last Transition Time:  2021-10-29T12:39:10Z
    Message:               the initial names have been accepted
    Reason:                InitialNamesAccepted
    Status:                True
    Type:                  Established
  Stored Versions:
    v1beta1
Events:  <none>
```
